// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a creative name for a dumpling combination.
 *
 * - generateDumplingName - A function that generates a creative name for a dumpling combination.
 * - GenerateDumplingNameInput - The input type for the generateDumplingName function.
 * - GenerateDumplingNameOutput - The return type for the generateDumplingName function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDumplingNameInputSchema = z.object({
  dumplingType: z.string().describe('The type of dumpling (e.g., Gyoza, Samosa, Pierogi).'),
  filling: z.string().describe('The filling of the dumpling (e.g., Scrambled Egg & Chorizo, Blueberry & Cream Cheese, Bacon & Cheddar).'),
});
export type GenerateDumplingNameInput = z.infer<typeof GenerateDumplingNameInputSchema>;

const GenerateDumplingNameOutputSchema = z.object({
  name: z.string().describe('A creative and appetizing name for the dumpling combination.'),
});
export type GenerateDumplingNameOutput = z.infer<typeof GenerateDumplingNameOutputSchema>;

export async function generateDumplingName(input: GenerateDumplingNameInput): Promise<GenerateDumplingNameOutput> {
  return generateDumplingNameFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDumplingNamePrompt',
  input: {schema: GenerateDumplingNameInputSchema},
  output: {schema: GenerateDumplingNameOutputSchema},
  prompt: `You are a creative food name generator. Given a type of dumpling and a filling, generate a creative and appetizing name for the combination.

Dumpling Type: {{{dumplingType}}}
Filling: {{{filling}}}

Name: `,
});

const generateDumplingNameFlow = ai.defineFlow(
  {
    name: 'generateDumplingNameFlow',
    inputSchema: GenerateDumplingNameInputSchema,
    outputSchema: GenerateDumplingNameOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
